---

- name: Test ansible
  hosts: localhost
  gather_facts: False

  tasks:
    - name: Touch the same file, but add/remove some permissions
      ansible.builtin.file:
        path: /tmp/test.ansible.file
        state: touch
        mode: u+rw,g-wx,o-rwx